# Generated by Django 4.2.5 on 2023-09-25 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemOptionValue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('available', models.BooleanField(default=True)),
                ('defaultoption', models.BooleanField(default=False)),
                ('pricechange', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ItemOptionValueImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('itemoptionvalue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.itemoptionvalue')),
            ],
            options={
                'unique_together': {('itemoptionvalue', 'photo')},
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OptionValue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.TextField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.TextField(unique=True),
        ),
        migrations.DeleteModel(
            name='ItemMaterial',
        ),
        migrations.DeleteModel(
            name='Material',
        ),
        migrations.AddField(
            model_name='itemoptionvalue',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item'),
        ),
        migrations.AddField(
            model_name='itemoptionvalue',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.option'),
        ),
        migrations.AddField(
            model_name='itemoptionvalue',
            name='optionvalue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.optionvalue'),
        ),
        migrations.AlterUniqueTogether(
            name='itemoptionvalue',
            unique_together={('item', 'option', 'optionvalue')},
        ),
    ]
